language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "10"
script:
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run publish
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true