language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "8"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > .npmrc
script:
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
before_deploy:
  - npm pack
  - npm publish --dry-run
  - git status
  - ls -l
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
